### ISSUE TITLE
Mocha Tests Timing Out

### ISSUE THREAD

**Issue by dschinkel** [rafinskipg/gulp-mocha-co#1]
I get timeouts after changing my mocha functions to be generators. 

Example:

```
    it('should return no country when no countries exist', function*(done){
        var countries = [];

        inMemoryGateway.data(countries);
        countryUseCase.gateway(inMemoryGateway);

        var request = testUtil.createCountryRequest();
        var responseModel = yield countryUseCase.find(request);
        should.not.exist(responseModel.countries);

        var request = testUtil.createCountryRequest(0, "", "", "");
        var responseModel = yield countryUseCase.find(request);
        should.not.exist(responseModel.countries);

        done();
    });
```
I end up getting:

```
Error: timeout of 8000ms exceeded
      at null.<anonymous> (/node_modules/gulp-mocha-co/node_modules/mocha-co/lib/runnable.js:175:14)
      at Timer.listOnTimeout (timers.js:89:15)
```

Here's the SUT code that my test is trying to yield the value from:

```
module.exports = {
    gateway: function(injectedGateway){
        if(injectedGateway){
            _gateway = injectedGateway;
        }
    },
    find: function *(countryRequest){
        if(!_gateway){
            _gateway = realGateway;
        }

        countryResponse.http.statusCode = 200;

        var entity = yield _gateway.find(countryRequest.id);

        if(!entity.countries || entity.countries.length == 0){
            entity.countries = null;
            countryResponse.http.statusCode = 204;
        }
        countryResponse.countries = entity.countries;

        return countryResponse;
    }
};
```

This code works fine in integration tests when called, it's just from my mocha tests am I having the timeout problem now that I've made all my mocha tests generators as you see above.

**Comment by rafinskipg** [comment]
Hi @dschinkel  I am not mantaining this module since a long time ago. If you want you can try to investige for the solution. 

Otherwise , i can try to arrange time in the future to look at it, but at this moment i can't

**Comment by dschinkel** [comment]
ok then please delete my thread, I don't want it lingering.  You should also put that this is no longer supported at the top so we don't realize it after the fact.  Thanks.

**Comment by dschinkel** [comment]
wrapped my generator test functions with co-wrap.  Resolved.

**Comment by dschinkel** [comment]
please delete this entire thread.
